FROM python:3.11-alpine

RUN apk add --no-cache socat openssl curl

WORKDIR /tests

COPY tests/haproxy/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY tests/haproxy/*.py ./
